"use client";

/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/KC1XnMsLLoX
 */
import Image from "next/image";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardHeader } from "@/components/ui/card";
import { GymForm } from "./gym-form";

export function GymMaker() {
  return (
    <main key="1" className="p-4 md:p-8">
      <div className="mx-auto max-w-[350px] space-y-6 md:max-w-[700px]">
        <div className="space-y-2 text-center">
          <TrafficConeIcon className="mx-auto mb-2 h-8 w-8" />
          <h1 className="text-3xl font-bold md:text-4xl">
            Criar Programa de Academia
          </h1>
          <p className="text-gray-500 dark:text-gray-400">
            Insira os detalhes para criar seu programa de academia
            personalizado.
          </p>
        </div>
        <GymForm />
      </div>
      <section className="mt-10">
        <Card className="mx-auto max-w-[350px] md:max-w-[700px]">
          <CardHeader>
            {/* <Avatar >
              <AvatarImage className="w-10 h-10 md:w-14 md:h-14" src="https://github.com/shadcn.png" />
              <AvatarFallback>CN</AvatarFallback>
            </Avatar> */}
            <div>
              <h2 className="text-xl font-bold md:text-2xl">
                Seu Programa de Academia
              </h2>
              <p className="text-sm text-gray-500 md:text-base dark:text-gray-400">
                Personalizado para suas necessidades
              </p>
            </div>
          </CardHeader>
          <CardContent>
            <Badge>Título do Programa</Badge>
            <p className="mt-2">Descrição do Programa</p>
            <p className="mt-2">Equipamento: Equipamento Disponível</p>
            <p className="mt-2">Objetivos: Objetivos do Usuário</p>
          </CardContent>
          <div className="p-4">
            <Image
              alt="Imagem do Programa"
              className="h-auto w-full"
              height="200"
              src="/placeholder.svg"
              style={{
                aspectRatio: "200/200",
                objectFit: "cover",
              }}
              width="200"
            />
          </div>
        </Card>
      </section>
    </main>
  );
}

function TrafficConeIcon(props: React.SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M9.3 6.2a4.55 4.55 0 0 0 5.4 0" />
      <path d="M7.9 10.7c.9.8 2.4 1.3 4.1 1.3s3.2-.5 4.1-1.3" />
      <path d="M13.9 3.5a1.93 1.93 0 0 0-3.8-.1l-3 10c-.1.2-.1.4-.1.6 0 1.7 2.2 3 5 3s5-1.3 5-3c0-.2 0-.4-.1-.5Z" />
      <path d="m7.5 12.2-4.7 2.7c-.5.3-.8.7-.8 1.1s.3.8.8 1.1l7.6 4.5c.9.5 2.1.5 3 0l7.6-4.5c.7-.3 1-.7 1-1.1s-.3-.8-.8-1.1l-4.7-2.8" />
    </svg>
  );
}
