"use client";

/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/KC1XnMsLLoX
 */
import Image from "next/image";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardHeader } from "@/components/ui/card";
import { GymForm } from "./gym-form";

export function GymMaker() {
  return (
    <main key="1" className="p-4 md:p-8">
      <div className="mx-auto max-w-[350px] space-y-6 md:max-w-[700px]">
        <div className="space-y-2 text-center">
          <DumbbellIcon className="mx-auto mb-2 h-8 w-8" />
          <h1 className="text-3xl font-bold md:text-4xl">
            Criar Programa de Academia
          </h1>
          <p className="text-gray-500 dark:text-gray-400">
            Insira os detalhes para criar seu programa de academia
            personalizado.
          </p>
        </div>
        <GymForm />
      </div>
      <section className="mt-10">
        <Card className="mx-auto max-w-[350px] md:max-w-[700px]">
          <CardHeader>
            {/* <Avatar >
              <AvatarImage className="w-10 h-10 md:w-14 md:h-14" src="https://github.com/shadcn.png" />
              <AvatarFallback>CN</AvatarFallback>
            </Avatar> */}
            <div>
              <h2 className="text-xl font-bold md:text-2xl">
                Seu Programa de Academia
              </h2>
              <p className="text-sm text-gray-500 md:text-base dark:text-gray-400">
                Personalizado para suas necessidades
              </p>
            </div>
          </CardHeader>
          <CardContent>
            <Badge>Título do Programa</Badge>
            <p className="mt-2">Descrição do Programa</p>
            <p className="mt-2">Equipamento: Equipamento Disponível</p>
            <p className="mt-2">Objetivos: Objetivos do Usuário</p>
          </CardContent>
          <div className="p-4">
            <Image
              alt="Imagem do Programa"
              className="h-auto w-full"
              height="200"
              src="/placeholder.svg"
              style={{
                aspectRatio: "200/200",
                objectFit: "cover",
              }}
              width="200"
            />
          </div>
        </Card>
      </section>
    </main>
  );
}

function DumbbellIcon(props: React.SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m6.5 6.5 11 11" />
      <path d="m21 21-1-1" />
      <path d="m3 3 1 1" />
      <path d="m18 22 4-4" />
      <path d="m2 6 4-4" />
      <path d="m3 10 7-7" />
      <path d="m14 21 7-7" />
    </svg>
  );
}
