/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/KC1XnMsLLoX
 */
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Textarea } from "@/components/ui/textarea"
import { Button } from "@/components/ui/button"
import { Avatar } from "@/components/ui/avatar"
import { CardHeader, CardContent, Card } from "@/components/ui/card"
import { Badge } from "@/components/ui/badge"
import Image from "next/image"

export function GymMaker() {
  return (
    <main key="1" className="p-4 md:p-8">
      <div className="mx-auto max-w-[350px] md:max-w-[700px] space-y-6">
        <div className="space-y-2 text-center">
          <TrafficConeIcon className="w-8 h-8 mx-auto mb-2" />
          <h1 className="text-3xl md:text-4xl font-bold">Criar Programa de Academia</h1>
          <p className="text-gray-500 dark:text-gray-400">
            Insira os detalhes para criar seu programa de academia personalizado.
          </p>
        </div>
        <div>
          <div className="space-y-4">
            <div className="space-y-2">
              <Label htmlFor="program-title">Título do Programa</Label>
              <Input id="program-title" placeholder="Insira o título do programa" required />
            </div>
            <div className="space-y-2">
              <Label htmlFor="program-description">Descrição do Programa</Label>
              <Textarea id="program-description" placeholder="Descreva seu programa" required />
            </div>
            <div className="space-y-2">
              <Label htmlFor="objectives">Objetivos do Usuário</Label>
              <Input id="objectives" placeholder="Descreva seus objetivos" required />
            </div>
            <div className="space-y-2 bg-blue-100 p-4 rounded-lg">
              <Label htmlFor="image-upload">Carregar Imagem / Tirar uma Foto</Label>
              <Input id="image-upload" required type="file" />
              <Button className="w-full mt-2 bg-blue-500 hover:bg-blue-700 text-white" type="button">
                Encontre Equipamento com IA
              </Button>
              <p className="text-sm text-gray-500 mt-1">
                Após carregar uma imagem, pressione o botão acima para preencher automaticamente o campo de equipamento.
              </p>
            </div>
            <div className="space-y-2">
              <Label htmlFor="equipment">Equipamento Disponível</Label>
              <Input id="equipment" placeholder="Lista de equipamentos disponíveis" required />
            </div>
            <Button className="w-full" type="submit">
              Criar Programa
            </Button>
          </div>
        </div>
      </div>
      <section className="mt-10">
        <Card className="mx-auto max-w-[350px] md:max-w-[700px]">
          <CardHeader>
            <Avatar className="w-10 h-10 md:w-14 md:h-14" src="/placeholder.svg?height=50&width=50" />
            <div className="ml-4">
              <h2 className="text-xl md:text-2xl font-bold">Seu Programa de Academia</h2>
              <p className="text-sm md:text-base text-gray-500 dark:text-gray-400">
                Personalizado para suas necessidades
              </p>
            </div>
          </CardHeader>
          <CardContent>
            <Badge>Título do Programa</Badge>
            <p className="mt-2">Descrição do Programa</p>
            <p className="mt-2">Equipamento: Equipamento Disponível</p>
            <p className="mt-2">Objetivos: Objetivos do Usuário</p>
          </CardContent>
          <div className="p-4">
            <Image
              alt="Imagem do Programa"
              className="w-full h-auto"
              height="200"
              src="/placeholder.svg"
              style={{
                aspectRatio: "200/200",
                objectFit: "cover",
              }}
              width="200"
            />
          </div>
        </Card>
      </section>
    </main>
  )
}


function TrafficConeIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M9.3 6.2a4.55 4.55 0 0 0 5.4 0" />
      <path d="M7.9 10.7c.9.8 2.4 1.3 4.1 1.3s3.2-.5 4.1-1.3" />
      <path d="M13.9 3.5a1.93 1.93 0 0 0-3.8-.1l-3 10c-.1.2-.1.4-.1.6 0 1.7 2.2 3 5 3s5-1.3 5-3c0-.2 0-.4-.1-.5Z" />
      <path d="m7.5 12.2-4.7 2.7c-.5.3-.8.7-.8 1.1s.3.8.8 1.1l7.6 4.5c.9.5 2.1.5 3 0l7.6-4.5c.7-.3 1-.7 1-1.1s-.3-.8-.8-1.1l-4.7-2.8" />
    </svg>
  )
}
